{
    "Advanced_Find":"Erweiterte Suche",
    "Site_Map":"Hauptmenü",
    "Nav_View_Duplicates":"Duplikate anzeigen",
    "NavBar_Collapsed_Caption":"NAVIGATION",
    "NavBar_Collapsed_ToolTip":"Navigations Leiste erweitern",
    "NavBar_DetailedPage_Area_AO":"Systemaufträge:",
    "NavBar_DetailedPage_Area_CS_SM":"Service",
    "NavBar_DetailedPage_Area_Header":"Verknüpft",
    "NavBar_DetailedPage_Area_IMA":"Internet Marketing",
    "NavBar_DetailedPage_Area_Info":"Allgemein",
    "NavBar_DetailedPage_Area_MA":"Marketing",
    "NavBar_DetailedPage_Area_PROC":"Prozesse",
    "NavBar_DetailedPage_Area_PROCESS":"Prozesssitzungen",
    "NavBar_DetailedPage_Area_SFA":"Vertrieb",
    "NavBar_Expanded_ToolTip":"Navigations Leiste reduzieren",
    "NavBar_Members_Area":"Mitglieder",
    "Area_Collateral":"Begleitmaterial",
    "Area_Collateral_Description":"Begleitmaterial",
    "Area_CustomerCenter":"Kundencenter",
    "Area_Goals":"Ziele",
    "Area_Goals_Description":"Ziele",
    "Area_Help":"Hilfe",
    "Area_Label_Appointment":"Termin",
    "Area_Label_Appointments":"Termine",
    "Area_Label_Cases":"Anfragen",
    "Area_Label_Info":"Informationen",
    "Area_Label_Kits":"Bausatz",
    "Area_Label_OtherContacts":"Andere Kontakte",
    "Area_Label_Partners":"Partner",
    "Area_Label_Sales":"Vertrieb",
    "Area_Marketing":"Marketing",
    "Area_ResourceCenter":"Kundencenter",
    "Area_Sales":"Vertrieb",
    "Area_Scheduling":"Planung",
    "Area_Service":"Service",
    "Area_Settings":"Einstellungen",
    "Area_Tab_Label_Scheduling":"Planung",
    "Area_Tab_Label_Work_Shift":"Arbeitszeit",
    "Area_Tools":"Tools",
    "Area_Tools_Description":"Tools",
    "Area_Workplace":"Arbeitsbereich",
    "HomeIcon_Tooltip":"Zur Startseite",
    "Homepage_Activities":"Aktivitäten",
    "Homepage_Administration":"Verwaltung",
    "Homepage_Alerts":"Warnungen",
    "Homepage_AppointmentBook":"Servicekalender",
    "Homepage_BusinessManagement":"Unternehmensmanagement",
    "Homepage_Calendar":"Kalender",
    "HomePage_CRM_Live_Title":"Microsoft Dynamics CRM Online",
    "HomePage_CRM_Logo_Title":"Microsoft Dynamics CRM",
    "Homepage_Dashboards":"Dashboards",
    "Homepage_DataManagement":"Datenverwaltung",
    "Homepage_DuplicateDetectionJobs":"Duplikaterkennung",
    "Homepage_Email":"CRM E-Mail",
    "Homepage_GettingStarted":"Erste Schritte",
    "Homepage_Home":"Meine Startseite",
    "Homepage_Import":"Importe",
    "Homepage_InteractiveWorkflows":"Dialoge",
    "Homepage_InternetLeadCapture":"Internet Lead Erfassung",
    "Homepage_InternetLeads":"Internet Leads",
    "Homepage_KBManager":"Artikel",
    "Homepage_Label_nav_accts":"Firmen-Manager",
    "Homepage_Label_nav_activities":"Aktivitäten-Manager",
    "Homepage_Label_nav_comps":"Mitbewerber-Manager",
    "Homepage_Label_nav_conts":"Kontakte-Manager",
    "Homepage_Label_nav_home":"Meine Startseite",
    "Homepage_Label_nav_invoices":"Rechnungs-Manager",
    "Homepage_Label_nav_leads":"Lead-Manager",
    "Homepage_Label_nav_onlinesvcs":"Online Services",
    "Homepage_Label_nav_oppts":"Verkaufschancen-Manager",
    "Homepage_Label_nav_orders":"Auftrags-Manager",
    "Homepage_Label_nav_products":"Produkt-Manager",
    "Homepage_Label_nav_quotes":"Angebots-Manager",
    "Homepage_Label_nav_saleslit":"Vertriebsdokumentations-Manager",
    "Homepage_LandingPages":"Landing Pages",
    "Homepage_LearningCustomization":"Verwaltung",
    "Homepage_LearningOverview":"Highlights",
    "Homepage_Marketplace":"Dynamics Marketplace",
    "Homepage_ProductCatalog":"Produkt Katalog",
    "Homepage_Queues":"Warteschlangen",
    "Homepage_Reports":"Berichte",
    "Homepage_Settings":"Einstellungen",
    "Homepage_SystemCustomization":"Anpassungen",
    "Homepage_SystemJobs":"Systemaufträge",
    "Homepage_Template":"Vorlagen",
    "Homepage_Title":"Meine Startseite",
    "Whats_New_Label":"Neuigkeiten",
    "Menu_Label_Business":"Unternehmen",
    "Menu_Label_Settings":"Einstellungen",
    "Menu_Label_Customizations":"Anpassungen",
    "Menu_Label_Home":"Startseite",
    "Menu_Label_ProcessCenter":"Processcenter",
    "Menu_Label_System":"System",
    "Group_Customers":"Kunden",
    "Group_Extensions":"Erweiterungen",
    "Group_Help":"Hilfe",
    "Group_MyWork":"Meine Arbeit",
    "Group_Sales":"Vertrieb",
    "Group_Salesperformance":"Vertriebs Performance",
    "DocumentManagement.SettingsArea.Heading":"Dokumentenverwaltung",
    "Audit_SubArea_Title":"Überwachung",
    "Social_SubArea_Title":"E-Mail-Konfiguration"
}