{
    "Advanced_Find":"Advanced Find",
    "Site_Map":"Site Map",
    "Nav_View_Duplicates":"View Duplicates",
    "NavBar_Collapsed_Caption":"NAVIGATION",
    "NavBar_Collapsed_ToolTip":"Expand Navigation Bar",
    "NavBar_DetailedPage_Area_AO":"System Jobs:",
    "NavBar_DetailedPage_Area_CS_SM":"Service",
    "NavBar_DetailedPage_Area_Header":"Related",
    "NavBar_DetailedPage_Area_IMA":"Internet Marketing",
    "NavBar_DetailedPage_Area_Info":"Common",
    "NavBar_DetailedPage_Area_MA":"Marketing",
    "NavBar_DetailedPage_Area_PROC":"Processes",
    "NavBar_DetailedPage_Area_PROCESS":"Process Sessions",
    "NavBar_DetailedPage_Area_SFA":"Sales",
    "NavBar_Expanded_ToolTip":"Collapse Navigation Bar",
    "NavBar_Members_Area":"Members:",
    "Area_Collateral":"Collateral",
    "Area_Collateral_Description":"Collateral",
    "Area_CustomerCenter":"Customer Center",
    "Area_Goals":"Goals",
    "Area_Goals_Description":"Goals",
    "Area_Help":"Help",
    "Area_Label_Appointment":"Appointment Book",
    "Area_Label_Appointments":"Appointments",
    "Area_Label_Cases":"Cases",
    "Area_Label_Info":"Information",
    "Area_Label_Kits":"Kit Products",
    "Area_Label_OtherContacts":"Other Contacts",
    "Area_Label_Partners":"Partners",
    "Area_Label_Sales":"Sales",
    "Area_Marketing":"Marketing",
    "Area_ResourceCenter":"Resource Center",
    "Area_Sales":"Sales",
    "Area_Scheduling":"Scheduling",
    "Area_Service":"Service",
    "Area_Settings":"Settings",
    "Area_Tab_Label_Scheduling":"Scheduling",
    "Area_Tab_Label_Work_Shift":"Work Shift",
    "Area_Tools":"Tools",
    "Area_Tools_Description":"Tools",
    "Area_Workplace":"Workplace",
    "HomeIcon_Tooltip":"Go to your Home page",
    "Homepage_Activities":"Activities",
    "Homepage_Administration":"Administration",
    "Homepage_Alerts":"Alerts",
    "Homepage_AppointmentBook":"Service Calendar",
    "Homepage_BusinessManagement":"Business Management",
    "Homepage_Calendar":"Calendar",
    "HomePage_CRM_Live_Title":"Microsoft Dynamics CRM Online",
    "HomePage_CRM_Logo_Title":"Microsoft Dynamics CRM",
    "Homepage_Dashboards":"Dashboards",
    "Homepage_DataManagement":"Data Management",
    "Homepage_DuplicateDetectionJobs":"Duplicate Detection",
    "Homepage_Email":"CRM Email",
    "Homepage_GettingStarted":"Get Started",
    "Homepage_Home":"My Home Page",
    "Homepage_Import":"Imports",
    "Homepage_InteractiveWorkflows":"Dialogs",
    "Homepage_InternetLeadCapture":"Internet Lead Capture",
    "Homepage_InternetLeads":"Internet Leads",
    "Homepage_KBManager":"Knowledge Base",
    "Homepage_Label_nav_accts":"Account Manager",
    "Homepage_Label_nav_activities":"Activity Manager",
    "Homepage_Label_nav_comps":"Competitor Manager",
    "Homepage_Label_nav_conts":"Contact Manager",
    "Homepage_Label_nav_home":"My Home Page",
    "Homepage_Label_nav_invoices":"Invoice Manager",
    "Homepage_Label_nav_leads":"Lead Manager",
    "Homepage_Label_nav_onlinesvcs":"Online Services",
    "Homepage_Label_nav_oppts":"Opportunity Manager",
    "Homepage_Label_nav_orders":"Order Manager",
    "Homepage_Label_nav_products":"Product Manager",
    "Homepage_Label_nav_quotes":"Quote Manager",
    "Homepage_Label_nav_saleslit":"Sale Literature Manager",
    "Homepage_LandingPages":"Landing Pages",
    "Homepage_LearningCustomization":"Administration",
    "Homepage_LearningOverview":"Highlights",
    "Homepage_Marketplace":"Dynamics Marketplace",
    "Homepage_ProductCatalog":"Product Catalog",
    "Homepage_Queues":"Queues",
    "Homepage_Reports":"Reports",
    "Homepage_Settings":"Settings",
    "Homepage_SystemCustomization":"Customization",
    "Homepage_SystemJobs":"System Jobs",
    "Homepage_Template":"Templates",
    "Homepage_Title":"My Home Page",
    "Whats_New_Label":"What's New",
    "Menu_Label_Business":"Business",
    "Menu_Label_Settings":"Settings",
    "Menu_Label_Customizations":"Customizations",
    "Menu_Label_Home":"Home",
    "Menu_Label_ProcessCenter":"Process Center",
    "Menu_Label_System":"System",
    "Group_Customers":"Customers",
    "Group_Extensions":"Extensions",
    "Group_Help":"Help",
    "Group_MyWork":"My Work",
    "Group_Sales":"Sales",
    "Group_Salesperformance":"Sales Performance",
    "DocumentManagement.SettingsArea.Heading":"Document Management",
    "Audit_SubArea_Title":"Auditing",
    "Social_SubArea_Title":"Email Configuration"






}